version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        container_name: web
        restart: unless-stopped
        dns:
            - 1.1.1.1
            - 1.0.0.1
        ports:
            - "23:22"
            - "8080:8080"
        depends_on:
            - php-fpm
            - mysql
        volumes:
            - ./html/logs:/home/gleb/html/logs

    php-fpm:
        build:
            context: .
            dockerfile: php-fpm.Dockerfile
        container_name: php-fpm
        restart: unless-stopped
        volumes:
            - ./html/logs:/var/www/html/logs

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: webchik
            MYSQL_ROOT_PASSWORD: "ZXGPK9tk7s0RPqp3Q8d1Hy5MZRw="
        volumes:
            - ./mysql:/var/lib/mysql
            - ./initdb:/docker-entrypoint-initdb.d
